/**
 * Keeps the docs "All commands" table (packages/web/.../reference/cli.md) in
 * sync with the CLI's real command registration — the same drift-protection the
 * Scanner docs get from @skillet/protocol, but build-time because the command
 * defs live in this Node package and can't be imported into a rendered page.
 *
 * The table is generated by walking the actual commander program built by
 * registerAllCommands (the single source — see register-all.ts / the tray-break
 * note in cli-command-tier.ts). This test fails if the committed table drifts
 * from that program. Regenerate with:
 *
 *   UPDATE_CLI_SNAPSHOT=1 pnpm --filter skilletmd test
 */
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";
import { Command, type Command as CommanderCommand } from "commander";
import { registerAllCommands } from "../src/commands/register-all.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOC_PATH = join(
  __dirname,
  "../../web/content/docs/cli.md",
);
const START = "<!-- cli-commands:start -->";
const END = "<!-- cli-commands:end -->";

type Row = { command: string; description: string };

/** Device surface only — legacy management verbs live in their own doc table. */
function buildProgram(): Command {
  const program = new Command("skillet").version("test");
  registerAllCommands(program, { legacyManagement: false });
  return program;
}

/**
 * Every runnable (leaf) command, full path, in registration order. A command
 * with visible subcommands isn't run alone, so we recurse into it rather than
 * emit it — matching what a user actually types.
 */
function collectRows(program: Command): Row[] {
  const rows: Row[] = [];
  const isHidden = (c: CommanderCommand): boolean =>
    Boolean((c as CommanderCommand & { _hidden?: boolean })._hidden);

  const walk = (cmd: CommanderCommand, path: string[]): void => {
    const subs = cmd.commands.filter((s) => !isHidden(s));
    // Emit this command when it's runnable itself (has an action) or is a leaf.
    // A pure group (e.g. `auth`, `route`) has no action and only recurses — but
    // a command like `add`, which both runs (`add <source>`) and owns a `kit`
    // subcommand, must appear as both `add` and `add kit`.
    const runnable = Boolean(
      (cmd as CommanderCommand & { _actionHandler?: unknown })._actionHandler,
    );
    if (runnable || subs.length === 0) {
      rows.push({ command: path.join(" "), description: (cmd.description() ?? "").trim() });
    }
    for (const sub of subs) walk(sub, [...path, sub.name()]);
  };

  for (const cmd of program.commands) {
    if (isHidden(cmd)) continue;
    walk(cmd, [cmd.name()]);
  }
  return rows;
}

function renderTable(rows: Row[]): string {
  const lines = ["| Command | What it does |", "|---|---|"];
  for (const r of rows) {
    const desc = r.description.replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|");
    lines.push(`| \`skillet ${r.command}\` | ${desc} |`);
  }
  return lines.join("\n");
}

test("docs CLI command table matches the real command registration", () => {
  const generated = renderTable(collectRows(buildProgram()));
  const doc = readFileSync(DOC_PATH, "utf8");
  const start = doc.indexOf(START);
  const end = doc.indexOf(END);
  assert.ok(start !== -1 && end !== -1, `cli.md is missing the ${START} / ${END} markers`);

  if (process.env["UPDATE_CLI_SNAPSHOT"] === "1") {
    const next = doc.slice(0, start + START.length) + "\n" + generated + "\n" + doc.slice(end);
    writeFileSync(DOC_PATH, next, "utf8");
    return;
  }

  const current = doc.slice(start + START.length, end).trim();
  assert.equal(
    current,
    generated,
    "The docs CLI command table is out of date. Run `UPDATE_CLI_SNAPSHOT=1 pnpm --filter skilletmd test` to regenerate it.",
  );
});
